/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  296: {
    TidepoolVault: {
      address: "0x2d209297642C4bb27c30ef37Fb18bCF842D55624",
      abi: [
        {
          inputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "pool",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "positionManager",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "swapRouter",
                  type: "address",
                },
                {
                  internalType: "int24",
                  name: "halfWidth",
                  type: "int24",
                },
                {
                  internalType: "uint32",
                  name: "twapWindow",
                  type: "uint32",
                },
                {
                  internalType: "int24",
                  name: "maxTwapDeviation",
                  type: "int24",
                },
                {
                  internalType: "uint32",
                  name: "rebalanceCooldown",
                  type: "uint32",
                },
                {
                  internalType: "uint16",
                  name: "swapSlippageBps",
                  type: "uint16",
                },
              ],
              internalType: "struct TidepoolVault.Config",
              name: "cfg",
              type: "tuple",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "AlreadyInitialized",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "readyAt",
              type: "uint256",
            },
          ],
          name: "CooldownActive",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "int64",
              name: "responseCode",
              type: "int64",
            },
          ],
          name: "HtsCallFailed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "required",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "provided",
              type: "uint256",
            },
          ],
          name: "InsufficientFee",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidConfig",
          type: "error",
        },
        {
          inputs: [],
          name: "NoPosition",
          type: "error",
        },
        {
          inputs: [],
          name: "NotDeployer",
          type: "error",
        },
        {
          inputs: [],
          name: "NotInitialized",
          type: "error",
        },
        {
          inputs: [],
          name: "NothingToCompound",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "int24",
              name: "spotTick",
              type: "int24",
            },
            {
              internalType: "int24",
              name: "twapTick",
              type: "int24",
            },
          ],
          name: "PriceDeviation",
          type: "error",
        },
        {
          inputs: [],
          name: "ReentrancyGuardReentrantCall",
          type: "error",
        },
        {
          inputs: [],
          name: "RefundFailed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint8",
              name: "bits",
              type: "uint8",
            },
            {
              internalType: "int256",
              name: "value",
              type: "int256",
            },
          ],
          name: "SafeCastOverflowedIntDowncast",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint8",
              name: "bits",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "SafeCastOverflowedUintDowncast",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "SafeCastOverflowedUintToInt",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "token",
              type: "address",
            },
          ],
          name: "SafeERC20FailedOperation",
          type: "error",
        },
        {
          inputs: [],
          name: "SlippageExceeded",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "int24",
              name: "twapTick",
              type: "int24",
            },
          ],
          name: "StillInRange",
          type: "error",
        },
        {
          inputs: [],
          name: "TwapUnavailable",
          type: "error",
        },
        {
          inputs: [],
          name: "ZeroShares",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "bool",
              name: "",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "",
              type: "bytes",
            },
          ],
          name: "CallResponseEvent",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "caller",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint128",
              name: "liquidityAdded",
              type: "uint128",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount0",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount1",
              type: "uint256",
            },
          ],
          name: "Compound",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "sender",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "receiver",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "shares",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount0",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount1",
              type: "uint256",
            },
          ],
          name: "Deposit",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint256",
              name: "fee0",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "fee1",
              type: "uint256",
            },
          ],
          name: "FeesCollected",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "shareToken",
              type: "address",
            },
          ],
          name: "Initialized",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "caller",
              type: "address",
            },
            {
              indexed: false,
              internalType: "int24",
              name: "twapTick",
              type: "int24",
            },
            {
              indexed: false,
              internalType: "int24",
              name: "oldTickLower",
              type: "int24",
            },
            {
              indexed: false,
              internalType: "int24",
              name: "oldTickUpper",
              type: "int24",
            },
            {
              indexed: false,
              internalType: "int24",
              name: "newTickLower",
              type: "int24",
            },
            {
              indexed: false,
              internalType: "int24",
              name: "newTickUpper",
              type: "int24",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "newPositionSerial",
              type: "uint256",
            },
          ],
          name: "Rebalance",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "receiver",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "shares",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount0",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount1",
              type: "uint256",
            },
          ],
          name: "Withdraw",
          type: "event",
        },
        {
          inputs: [],
          name: "DEAD_SHARES",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "INITIAL_SHARES",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "SHARE_DECIMALS",
          outputs: [
            {
              internalType: "int32",
              name: "",
              type: "int32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "compound",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "deployer",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "amount0Max",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "amount1Max",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "minShares",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "receiver",
              type: "address",
            },
          ],
          name: "deposit",
          outputs: [
            {
              internalType: "uint256",
              name: "shares",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "amount0",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "amount1",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "factory",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "fee",
          outputs: [
            {
              internalType: "uint24",
              name: "",
              type: "uint24",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getPriceState",
          outputs: [
            {
              internalType: "int24",
              name: "spotTick",
              type: "int24",
            },
            {
              internalType: "int24",
              name: "twapTick",
              type: "int24",
            },
            {
              internalType: "bool",
              name: "inRange",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getTotalAmounts",
          outputs: [
            {
              internalType: "uint256",
              name: "total0",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "total1",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "halfWidth",
          outputs: [
            {
              internalType: "int24",
              name: "",
              type: "int24",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "symbol",
              type: "string",
            },
          ],
          name: "initialize",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "lastRebalance",
          outputs: [
            {
              internalType: "uint64",
              name: "",
              type: "uint64",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "maxTwapDeviation",
          outputs: [
            {
              internalType: "int24",
              name: "",
              type: "int24",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "pool",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "positionManager",
          outputs: [
            {
              internalType: "contract ISaucerSwapV2NonfungiblePositionManager",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "positionNft",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "positionSerial",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "quoteMintFee",
          outputs: [
            {
              internalType: "uint256",
              name: "tinybars",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "rebalance",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "rebalanceCooldown",
          outputs: [
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "shareToken",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "swapRouter",
          outputs: [
            {
              internalType: "contract ISaucerSwapV2SwapRouter",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "swapSlippageBps",
          outputs: [
            {
              internalType: "uint16",
              name: "",
              type: "uint16",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "tickLower",
          outputs: [
            {
              internalType: "int24",
              name: "",
              type: "int24",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "tickSpacing",
          outputs: [
            {
              internalType: "int24",
              name: "",
              type: "int24",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "tickUpper",
          outputs: [
            {
              internalType: "int24",
              name: "",
              type: "int24",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "token0",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "token1",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalShares",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "twapWindow",
          outputs: [
            {
              internalType: "uint32",
              name: "",
              type: "uint32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "shares",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "amount0Min",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "amount1Min",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "receiver",
              type: "address",
            },
          ],
          name: "withdraw",
          outputs: [
            {
              internalType: "uint256",
              name: "amount0",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "amount1",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 40957955,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
